### ISSUE TITLE
Year is out of range

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#1]
Not certain the data that leads to this but it seems to be a timestamp issue

```
Traceback (most recent call last):
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module>
    sys.exit(TapPostgres.cli())
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 506, in cli
    tap.sync_all()
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 379, in sync_all
    stream.sync()
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 1045, in sync
    self._sync_records(context)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 971, in _sync_records
    for record_result in self.get_records(current_context):
  File "/home/visch/git/tap-postgres/tap_postgres/client.py", line 40, in get_records
    yield from super().get_records(partition)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/streams/sql.py", line 1019, in get_records
    for row in self.connector.connection.execute(query):
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 382, in iterrows
    for row in self._fetchiter_impl():
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1795, in _fetchiter_impl
    row = fetchone(self, self.cursor)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1083, in fetchone
    self._buffer_rows(result, dbapi_cursor)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1055, in _buffer_rows
    self.handle_exception(result, dbapi_cursor, e)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2047, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1053, in _buffer_rows
    new_rows = dbapi_cursor.fetchmany(size)
ValueError: year -1 is out of range
```

**Comment by jcbmllgn** [comment]
I'm experiencing the same issue, when running `meltano invoke tap-postgres > postgres.json` I'm getting these logs:


```
ime=2023-04-24 11:46:10 name=tap_postgres level=INFO message=Beginning new Full Table replication 1682329566975
time=2023-04-24 11:46:10 name=tap_postgres level=INFO message=select SELECT  "chart_id" , "chat_url" , "city" ,CASE WHEN  "created_at"  < '0001-01-01 00:00:00.000' OR  "created_at"  > '9999-12-31 23:59:59.999' THEN '9999-12-31 23:59:59.999' ELSE  "created_at"  END AS  "created_at" , "date_of_birth" , "email" , "emr_url" , "family_name" , "gender" , "given_name" , "id" , "language" , "middle_name" , "postal_code" , "preferences" , "preferred_provider_id" , "source" , "state" , "street_1" , "street_2" ,CASE WHEN  "updated_at"  < '0001-01-01 00:00:00.000' OR  "updated_at"  > '9999-12-31 23:59:59.999' THEN '9999-12-31 23:59:59.999' ELSE  "updated_at"  END AS  "updated_at" , xmin::text::bigint
                                      FROM "public"."extra_profiles"
                                     ORDER BY xmin::text ASC with itersize 20000
time=2023-04-24 11:46:19 name=singer level=INFO message=METRIC: {"type": "counter", "metric": "record_count", "value": 37762, "tags": {}}
time=2023-04-24 11:46:19 name=tap_postgres level=CRITICAL message=year -1 is out of range
Traceback (most recent call last):
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module>
    sys.exit(main())
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 448, in main
    raise exc
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 445, in main
    main_impl()
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 434, in main_impl
    do_sync(conn_config, args.catalog.to_dict() if args.catalog else args.properties,
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 312, in do_sync
    state = sync_traditional_stream(conn_config,
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 172, in sync_traditional_stream
    state = do_sync_full_table(conn_config, stream, state, desired_columns, md_map)
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/__init__.py", line 63, in do_sync_full_table
    state = full_table.sync_table(conn_config, stream, state, desired_columns, md_map)
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/tap_postgres/sync_strategies/full_table.py", line 144, in sync_table
    for rec in cur:
  File "/Users/jacob/code/pairteam/analytics-etl/.meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/psycopg2/extras.py", line 120, in __iter__
    yield next(res)
ValueError: year -1 is out of range
```

@visch, did you end up figuring something out?

**Comment by visch** [comment]
@jcbmllgn I'll be looking at this soon (Probably tomorrow) to get a fix. iirc it's something to do with Date's being either Null or empty but it's been a while so I'm guessing

**Comment by jcbmllgn** [comment]
With the help of @z3z1ma I'm pretty sure that the issue is that this `extra_profiles` table has a date column with a date from year -1. This is an issue in our source database we'll work to fix, we shouldn't have users with DOB before year zero! But this also seems like something that the postgres tap should handle gracefully.

**Comment by z3z1ma** [comment]
@visch 

The fact of the matter is there is no "correct" way to represent a native date type with a negative year in Python. So its a tradeoff. By finding some way to support it, you lose correctness because you are now choosing a way to interpret potentially valid information by either NULL'ing it or turning it into a string or some such. I understand why the psycopg maintainers (which is the layer in which this needs to be addressed, made the choices they did). They chose correctness over runtime safety. 

Here is an example on the path to modifying the behavior:
https://www.psycopg.org/psycopg3/docs/advanced/adapt.html#example-handling-infinity-date

I would recommend it be put behind a config variable and forcing it to be opt-in so to prefer correctness.

**Comment by visch** [comment]
@z3z1ma thanks for the write up, you're right this is a psycopg issue. 

Thought about this a decent amount and did some deep diving. In postgres you can push some pretty interesting dates into date fields like BCE years -44 etc etc, all of which are not "valid" dates from a jsonschema standpoint.

I think the current behavior actually does make a lot of sense, but we should allow folks to override the `type` to be a String. I tried overriding the `format` for a value and it doesn't work as we'd need to covert / cast the value before `psycopg` touches it makes a lot of sense. While we could format dates differently like you recommend @z3z1ma  I think that's too opinionated and will lead us into trouble (hence your recommendation of a configuration value). 

Switching this to a `feature` request. A meltano.yml like

```
    select:
    - '!information_schema*'
    - public-newtable.*
    schema:
      public-newtable:
        date:
          type: [string, 'null']
          format: null
``` 

ie a catalog like
```
   {
      "tap_stream_id": "public-newtable",
      "table_name": "newtable",
      "replication_method": "",
      "key_properties": [],
      "schema": {
        "properties": {
          "date": {
            "type": [
              "string",
              "null"
            ],
            "format": {}
          }
        },
        "type": "object"
      }

```

Seems like a decent approach, but the issue with this approach is that you'd have to rely on the `catalog` for type mappings instead of https://github.com/meltano/sdk/blob/b5baaa01eae552de0ef369cba8bf5386190e6a27/singer_sdk/connectors/sql.py#LL586C19-L586C28 using `sqlalchemy`'s inspector. 

It seems to me this wouldn't be a horrible approach as `discovery` will use the inspector for you and then you "should" be ok, but I'm not super sure here. Curious what people think!


@jcbmllgn  right now the best workaround is to either not select the offending column, or create a view in your database that converts the date to a string. Sorry this isn't the best! (Pipelinewise variant has this same behavior)

**Comment by jcbmllgn** [comment]
We were able to work around this issue by fixing the dates upstream. It was a bug in a source system, which we have control over, that there were BC dates. We fixed the data upstream and we're now successfully syncing these tables.

**Comment by visch** [comment]
@z3z1ma thanks for the pointers here!

@jcbmllgn glad you have this working, we have a fix in place now!
