### ISSUE TITLE
Decimal Typing Issue

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#150]
```
2023-06-09T21:25:39.282265Z [info     ] 2023-06-09 21:25:39,281 | INFO     | tap-postgres         | Tap has custom mapper. Using 1 provided map(s). cmd_type=elb consumer=False name=tap-postgres producer=True stdio=stderr string_id=tap-postgres
2023-06-09T21:25:39.427416Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.427997Z [info     ]   File "/project/.meltano/loaders/target-jsonl/venv/bin/target-jsonl", line 8, in <module> cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.428957Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.429355Z [info     ]   File "/project/.meltano/loaders/target-jsonl/venv/lib/python3.9/site-packages/target_jsonl.py", line 92, in main cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.429705Z [info     ]     state = persist_messages(  cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.430096Z [info     ]   File "/project/.meltano/loaders/target-jsonl/venv/lib/python3.9/site-packages/target_jsonl.py", line 54, in persist_messages cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.430436Z [info     ]     validators[o['stream']].validate((o['record'])) cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.430789Z [info     ]   File "/project/.meltano/loaders/target-jsonl/venv/lib/python3.9/site-packages/jsonschema/validators.py", line 130, in validate cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.431137Z [info     ]     raise error                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.431486Z [info     ] jsonschema.exceptions.ValidationError: Decimal('18.23') is not of type 'string', 'null' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.431865Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.432251Z [info     ] Failed validating 'type' in schema['properties']['time_on_page']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.432639Z [info     ]     {'type': ['string', 'null']} cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.433023Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.433749Z [info     ] On instance['time_on_page']:   cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.434078Z [info     ]     Decimal('18.23')           cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-06-09T21:25:39.455847Z [error    ] Loader failed
2023-06-09T21:25:39.456357Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False

```

To replicate data setup run `meltano run tap-smoke-test target-postgres`

```
version: 1
default_environment: dev
project_id: 8210a9d4-e3f1-4674-a9c3-b66fefda9ba6
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-smoke-test
    variant: meltano
    pip_url: git+https://github.com/meltano/tap-smoke-test.git
    config:
      streams:
      - stream_name: animals
        input_filename: https://gitlab.com/meltano/tap-smoke-test/-/raw/main/demo-data/animals-data.jsonl
      - stream_name: page_views
        input_filename: https://gitlab.com/meltano/tap-smoke-test/-/raw/main/demo-data/pageviews-data.jsonl
      stream_maps:
        animals:
          __key_properties__: [id]
        page_views:
          __key_properties__: [vistor_id]
  loaders:
  - name: target-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-postgres.git
    config:
      database: postgres
      host: localhost
      user: postgres
```

Then from that postgres instance run `meltano run tap-postgres target-jsonl`

**Comment by visch** [comment]
Another instance of this issue https://meltano.slack.com/archives/C01TCRBBJD7/p1688666046853549
